import { AlertTriangle } from "lucide-react";

const Disclaimer = () => {
  return (
    <div className="container max-w-2xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-display font-bold text-foreground mb-6">
        Disclaimer
      </h1>

      {/* Prominent warning box */}
      <div className="bg-destructive/10 border border-destructive/30 rounded-lg p-4 mb-8 flex gap-3">
        <AlertTriangle className="w-6 h-6 text-destructive flex-shrink-0 mt-0.5" />
        <div>
          <p className="font-semibold text-foreground mb-2">Important Notice</p>
          <p className="text-sm text-muted-foreground">
            FastTrack.Business does NOT provide legal, accounting, tax, or financial advice. 
            The information and AI-generated content on this platform is for educational and 
            informational purposes only.
          </p>
        </div>
      </div>

      <div className="prose prose-sm max-w-none space-y-6 text-muted-foreground">
        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">
            General Information Only
          </h2>
          <p>
            The content provided by FastTrack.Business, including AI-generated business ideas, 
            reports, and recommendations, is intended for general informational purposes only. 
            It should not be construed as professional advice of any kind.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">
            No Guarantees
          </h2>
          <p>
            We make no guarantees regarding the success, profitability, or viability of any 
            business ideas generated by our platform. Business success depends on numerous 
            factors beyond our control, including but not limited to market conditions, 
            individual effort, timing, and execution.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">
            Seek Professional Advice
          </h2>
          <p>
            Before starting any business venture, you should consult with qualified professionals, including:
          </p>
          <ul className="list-disc list-inside mt-2 space-y-1">
            <li>A licensed lawyer for legal matters</li>
            <li>A certified accountant for tax and financial matters</li>
            <li>A business advisor for strategic planning</li>
            <li>Industry-specific experts as needed</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">
            AI Limitations
          </h2>
          <p>
            Our AI-generated content is based on patterns and data available at the time of 
            generation. It may not reflect the most current market conditions, regulations, 
            or opportunities. AI can make errors, and its suggestions should be validated 
            independently.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">
            User Responsibility
          </h2>
          <p>
            You are solely responsible for any decisions made based on information provided 
            by FastTrack.Business. We shall not be held liable for any losses, damages, or 
            negative outcomes resulting from the use of our platform or its content.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">
            Canadian Context
          </h2>
          <p>
            While our platform focuses on Canadian business opportunities, regulations and 
            requirements vary by province and territory. Always verify local requirements 
            with appropriate government agencies.
          </p>
        </section>
      </div>

      <p className="text-sm text-muted-foreground mt-8 pt-6 border-t border-border">
        Last updated: {new Date().toLocaleDateString("en-CA")}
      </p>
    </div>
  );
};

export default Disclaimer;
